if (args.Contains("--restore-audio-state")) return OperatingSystem.IsWindows() ? AudioRecoveryCommand.Run(args) : 1;
if (args.Contains("--apo-lease-probe")) return OperatingSystem.IsWindows() ? ApoObjectLeaseTests.Probe(args) : 1;
if (args.Contains("--hardware-effects")) return OperatingSystem.IsWindows() ? HardwareEffectsTests.Run(args) : 1;
if (args.Contains("--hardware-playback")) return OperatingSystem.IsWindows() ? HardwarePlaybackTests.Run(args) : 1;
if (args.Contains("--hardware-loopback")) return OperatingSystem.IsWindows() ? HardwareLoopbackTests.Run(args) : 1;
if (args.Contains("--hardware-audio")) return HardwareAudioTests.Run(args);
if (args.Contains("--topology")) return TopologyDiagnostics.Run(args);
if (args.Contains("--hardware-sidetone")) return HardwareSidetoneTests.Run(args);
if (args.Contains("--hardware-gsx-sidetone")) return OperatingSystem.IsWindows() ? HardwareGsxSidetoneTests.Run(args) : 1;
if (args.Contains("--monitor-packets")) return OperatingSystem.IsWindows() ? MonitorPacketDiagnostics.Run(args) : 1;
if (args.Contains("--dependencies")) return DependencyDiagnostics.Run(args);
var suite = new TestSuite();
try { ExistingTests.Run(suite); } catch (Exception ex) { suite.Case("Existing regression suite setup", () => throw ex); }
EffectsTests.Run(suite);
GsxMicrophoneTests.Run(suite);
ControlDiagnosticsTests.Run(suite);
GsxSidetoneEvidenceTests.Run(suite);
GsxSidetoneTests.Run(suite);
PlaybackTests.Run(suite);
ReverbTests.Run(suite);
LiveApplyTests.Run(suite);
ProfileWorkflowTests.Run(suite);
ApplicationStorageTests.Run(suite);
SetupProfileTests.Run(suite);
B20ProcessingTests.Run(suite);
ProfileEffectsTests.Run(suite);
AudioValidationTests.Run(suite);
MicrophoneMonitorTests.Run(suite);
SidetoneTests.Run(suite);
PickupPatternTests.Run(suite);
ApoObjectLeaseTests.Run(suite);
ApoInitializationTests.Run(suite);
ApoStartupStateTests.Run(suite);
GsxInitializationTests.Run(suite);
GsxPreparedDiscoveryTests.Run(suite);
AudioRecoveryTests.Run(suite);
ProcessingStateTests.Run(suite);
B20HostLifecycleTests.Run(suite);
suite.Report(args);
return suite.Failures == 0 ? 0 : 1;
